export const subjects = [
    { value: "leadership1", label: "Leadership UEB" },
    { value: "bas1221", label: "Pháp luật đại cương"},
    { value: "bas1221_more", label: "Pháp luật đại cương (Premium)" },
    { value: "bas1221_1", label: "Pháp luật đại cương (Chương 1)" },
    { value: "bas1221_2", label: "Pháp luật đại cương (Chương 2)" },
    { value: "bas1221_3", label: "Pháp luật đại cương (Chương 3)" },
    { value: "bas1221_4", label: "Pháp luật đại cương (Chương 4)" },
    { value: "bas1221_5", label: "Pháp luật đại cương (Chương 5)" },
    { value: "bas1221_6", label: "Pháp luật đại cương (Chương 6)" },
    { value: "bas1221_7", label: "Pháp luật đại cương (Chương 7)" },
    { value: "bas1221_8", label: "Pháp luật đại cương (Chương 8)" },
    { value: "bas1221_9", label: "Pháp luật đại cương (Chương 9)" },
    { value: "int1336", label: "Mạng máy tính" },
    { value: "mar1333_1", label: "Internet và Ứng dụng trong kinh doanh (Chương 1)" },
    { value: "mar1333_2", label: "Internet và Ứng dụng trong kinh doanh (Chương 2)" },
    { value: "bas1122", label: "Tư tưởng Hồ Chí Minh"},
    { value: "bas1122_lms", label: "Tư tưởng Hồ Chí Minh (LMS)"},
    { value: "bas1122_2", label: "Tư tưởng Hồ Chí Minh (Chương 2)" },
    { value: "bas1122_3", label: "Tư tưởng Hồ Chí Minh (Chương 3)" },
    { value: "bas1122_4", label: "Tư tưởng Hồ Chí Minh (Chương 4)" },
    { value: "bas1122_5", label: "Tư tưởng Hồ Chí Minh (Chương 5)" },
    { value: "bas1122_6", label: "Tư tưởng Hồ Chí Minh (Chương 6)" },
];